@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "org.example.contacts.dao.ContactDAO",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1373648983 { 
   	label=contacts
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ContactDAO770836037[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)ContactDAO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(id: long): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByName(name: String): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(newContact: Contact): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

ContactDummyDAO770836037[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ContactDummyDAO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(id: long): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByName(name: String): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(newContact: Contact): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ContactFileDAO770836037[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ContactFileDAO</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ delete(id: long): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByName(name: String): List&lt;Contact&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(newContact: Contact): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Controller1699348873[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Controller</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dao: ContactDAO [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listView: ListView&lt;Contact&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nameField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numberField: TextField [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   searchField: TextField [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ initialize()</TD></TR>
<TR><TD ALIGN="LEFT" ># onDelete(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" ># onSave(event: ActionEvent)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onSearch(actionEvent: ActionEvent)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ContactDAO770836037 -> ContactDummyDAO770836037[arrowhead=none, arrowtail=empty, dir=both];
ContactDAO770836037 -> ContactFileDAO770836037[arrowhead=none, arrowtail=empty, dir=both];
Controller1699348873 -> ContactDAO770836037[label="dao
[0..1]"];
    
}
@enduml